# Generated by Django 5.2 on 2025-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
            ],
            options={
                'verbose_name': 'IDC机房',
                'verbose_name_plural': 'IDC机房',
                'db_table': 'cmdb_idc',
            },
        ),
    ]
