# Generated by Django 5.2 on 2025-05-07 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_rack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['-id'], 'verbose_name': 'IDC机房', 'verbose_name_plural': 'IDC机房'},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['-id'], 'verbose_name': '机柜', 'verbose_name_plural': '机柜'},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='idc',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='idc',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='idc',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='rack',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='rack',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='rack',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterUniqueTogether(
            name='idc',
            unique_together={('name',)},
        ),
    ]
