# Generated by Django 5.2 on 2025-05-07 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_alter_idc_options_alter_rack_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('password', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='SSH 密码')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
    ]
