# Generated by Django 5.2 on 2025-05-07 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_sshuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('ssh_ip', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='SSH IP地址/主机名')),
                ('ssh_port', models.IntegerField(blank=True, default=22, max_length=5, null=True, verbose_name='SSH 端口')),
                ('uuid', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='UUID')),
                ('cpu', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='磁盘大小')),
                ('system_product', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='服务器类型')),
                ('daq', models.TextField(blank=True, default='', null=True, verbose_name='数据采集')),
                ('status', models.CharField(choices=[('0', '下线'), ('1', '在线')], default='1', max_length=2, verbose_name='运行状态')),
                ('rack', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.rack', verbose_name='所属机柜')),
                ('ssh_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.sshuser', verbose_name='SSH用户')),
                ('users', models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL, verbose_name='业务相关的用户')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
