# Generated by Django 5.2 on 2025-05-12 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.idc', verbose_name='所属机房'),
        ),
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('users', models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('language_type', models.CharField(blank=True, choices=[('python', 'python'), ('java', 'java'), ('php', 'php'), ('golang', 'golang')], default='', max_length=256, null=True, verbose_name='语言类型')),
                ('repo_url', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='版本库地址')),
                ('jenkins_job', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='JENKINS JOB')),
                ('status', models.CharField(choices=[('0', '启用'), ('1', '停用')], default='0', max_length=2, verbose_name='状态')),
                ('businesses', models.ManyToManyField(blank=True, default='', null=True, to='cmdb.businessline', verbose_name='所属业务线')),
                ('servers', models.ManyToManyField(blank=True, default='', null=True, to='cmdb.server', verbose_name='相关服务器')),
                ('users', models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
    ]
